server:
  port: 8080
  servlet:
    context-path: /
    enableLoggingRequestDetails: true
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: lomelodb
      uri: mongodb://localhost:27017/lomelodb

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG